// Datei: chronik.js
// Projekt: Textbausteine — Teil: App (Browser)
// Zweck: Die Entwicklungs-Chronik in der App: welche Etappe wann
//        gebaut wurde, was sie brachte und welche besonderen Momente
//        es gab. Wird bei jeder Abnahme um einen Eintrag ergänzt
//        (Teil des Quartetts).

"use strict";
window.TB = window.TB || {};

TB.chronik = (function () {
  // Neueste zuoberst. [Zeitraum, Titel, Was, Besonderer Moment]
  function eintraege() {
    return [
      ["1.\u20132.10.2026", "Etappe 10: Das EEG-Werk als Schnell-Befund",
       "Der EEG-Befund in Sekunden: Die h\u00e4ufigen Kategorien stehen offen und vorausgef\u00fcllt (Technik-Satz, Artefakte, Grundrhythmus mit Frequenzfeld, Vigilanz, Hyperventilation, Photostimulation, EKG), Seltenes \u2014 Vor-EEG, Anfallsmuster, die periodischen Muster der Intensivstation, Salzburg-Kriterien, Normvarianten, Knochenl\u00fccke, klinische Ereignisse \u2014 ist eingeklappt und erscheint nur auf Aufklappen. Verlangsamungsherde und Entladungen sind Zeilen: H\u00e4ufigkeit, Band oder Form, bis vier Lokalisations-K\u00e4stchen als Kette (frontal+temporal wird fronto-temporal, temporal+frontal wird temporo-frontal; auch generalisiert und hemisph\u00e4risch), Ausbreitung und Seite \u2014 weitere Zeilen per + Herd und + Entladung. Die BEURTEILUNG entsteht automatisch aus dem Befund: Grundrhythmus unter 8 Hz ergibt die leichte, unter 6 Hz die mittelschwere Allgemeinver\u00e4nderung; jedes Band seinen Herd-Schweregrad von leicht (Theta) bis schwer (Delta; Subdelta mit Zusatz); fGRDA mit einem Kreuz. Jeder automatische Satz l\u00e4sst sich anklicken und \u00fcberschreiben. Zwei Vorlagen: Normal (;;eeg) und IPS (;;eegips); eigene Vorlagen samt Zeilen-Muster und eigenem K\u00fcrzel jederzeit speicherbar.",
       "Die erste Fassung baute das EEG wie den Status \u2014 ein grosser Katalog zum Ankreuzen. N\u00e4ds erster Blick drehte das Werk um: Die meisten EEGs sind simpel, das H\u00e4ufigste (die Herde) muss das Einfachste sein, und die Beurteilung will er nie selbst schreiben. Daraus wurde der Schnell-Befund mit Beurteilungs-Automatik \u2014 und die Erkenntnis, dass \u00dcberschriebenes hier kein Fett braucht: Im EEG steht nur, was auff\u00e4llig ist."],
      ["26.9.–1.10.2026", "Etappe 9: Status-Werk, Bericht Memory Clinic — und die Praxis-Werkzeuge",
       "Ein Gesamtstatus mit rund 190 Untersuchungen in 13 Kategorien, aus dem die einzelnen Status als Auswahlen entstehen: Normalbefunde überschreiben (nur der veränderte Teil fett und dunkelgrau), Einzelmuskeln an- und abwählen, eigene Status mit Zusätzen (sichtbar, aber nicht angekreuzt), Ziehen in der Katalog-Pflege und eine Tardoc-Ampel, die laufend sagt, ob die Auswahl für Neurostatus und Hirnnervenstatus A oder B reicht und was fehlt. Dazu der zweite echte Bericht: ;;bermc baut aus dem neuropsychologischen Vorbericht und eingelesenen Befunden — EEG-Brief, Radiologie, Viollier-Demenzmarker, LP-Punktat oder der ganze KISIM-Untersuchungsblock auf einmal — die KISIM-Felder Anamnese und Untersuchungen und springt selbst von Feld zu Feld. Für die Praxis entstanden in der Chrome-Erweiterung die MRI-Anmeldung an vier Institute mit fertiger Outlook-Mail und die Patienten-Kette für die Excel-Liste. Dazu eine Bausteine-Übersicht mit PDF.",
       "Drei Lektionen der härteren Art. Das Windows-Skript verlor im Betrieb still seine Tastenüberwachung — gefunden nur, weil ein Zähler beim Tippen stehenblieb; seither setzt ein Wächter sie jede Minute neu auf. Die Praxis-MRI wurde zuerst als Skript gebaut, obwohl Smart App Control dort seit Wochen jedes Skript verbietet — ein Blick in die eigene Übergabe hätte es verhindert; der Neubau in der Erweiterung war am selben Tag fertig und „funktioniert perfekt“. Und ein Geburtsdatum schlüpfte zweimal als Untersuchungsdatum durch, bis die Regel nicht mehr auf Wörter achtete, sondern auf Plausibilität: Ein Datum von 1941 kann kein Untersuchungstag sein."],
      ["24.–25.9.2026", "Etappe 8: Masken und der erste echte Bericht",
       "Bausteine können jetzt fragen, bevor sie schreiben: Kästchen schalten ganze Abschnitte an und ab (Wenn/WennNicht bis in die Verschachtelung), Ankreuz-Sätze lassen sich vor dem Einsetzen überschreiben, Auswahllisten steuern Folgesätze, und {{Aus Kategorie:…}} holt andere Bausteine der Reihe nach dazu — in der App, in der Chrome-Erweiterung und im Windows-Skript, wo {{Sprung:…}} per Strg+Tab durch die KISIM-Feldmaske führt. Im Bearbeiten-Fenster wurden die Klammer-Codes durch anklickbare Kärtchen ersetzt (Paare in gleicher Farbe, Fehlendes rot gestrichelt, Rohtext auf Wunsch). Fertige Bausteine brauchen seither ein Kürzel, Kategorien zeigen wieder alle ihre Bausteine. Und als Krönung der erste echte Baustein dieser Grösse: ;;ber, der ambulante neurologische Bericht — zehn Anamnese-Kapitel, Status- und Untersuchungs-Wahl, in der Praxis mit Titeln, am Spital durch die Felder springend bis zur Schreibmarke in Procedere.",
       "Drei zähe Gegner: KISIM stürzte mit „Invalid memory read/write“ ab, weil verschachtelte Fenster-Rückrufe zu früh freigegeben wurden — seither führt eine flache Zustands-Kette durch die Fenster. Die Leerzeilen des Berichts verschwanden je Weg anders: Browser zeigen einen Umbruch am Absatzende nicht an, und im RTF liess jedes abgewählte Kapitel eine Absatzmarke zurück — geheilt wurde beides, im Text UND im Druckformat, mit einem geschützten Leerzeichen als Leerzeilen-Träger. Und die ehrlichste Erkenntnis: Das Masken-KONZEPT bleibt für den Anwender schwer — der Vergleich zeigte, dass TextExpander es mit denselben Marken genauso macht. Die Antwort sind Kochbuch, Vorlage und ein künftiger Frage-Assistent, nicht mehr Erklärtext."],
      ["23.9.2026", "Etappe 7: Tabellen",
       "Tabellen aus KISIM kommen jetzt als Tabellen an — mit verbundenen Zellen, seitengenauen Linien, Spaltenbreiten, Hintergründen und Zentrierung. Die Duplex-Vorlage mit ihrer hohen Legendenzelle war der Prüfstein. Dazu Werkzeuge für Zeilen und Spalten, Spaltenbreite in Stufen, Ausrichtung und Hintergrund je Zelle, Zellen verbinden und lösen, und ein Knopf für ganz neue Tabellen. Die Häkchen stehen einheitlich als ✓, das Durchmesserzeichen als ø. Neu lässt sich ausserdem jeder Baustein kopieren: der Inhalt wird übernommen, Titel und Kürzel müssen neu vergeben werden. Das Windows-Skript holt den Nachschub nun alle dreissig Sekunden selbst — vorher fragt es in einem winzigen Ruf, ob sich überhaupt etwas geändert hat.",
       "Zwei Fehler versteckten sich hinter derselben Annahme: dass die App wisse, wie eine Tabelle auszusehen hat. Sie wusste es nur im eigenen Fenster — in Word, Axenita und der Erweiterung stand dieselbe Tabelle nackt und zusammengeschrumpft da, weil sie ihre Linien und ihre Breite vom Stilblatt der App borgte statt sie selbst mitzubringen. Und ein Zeichen in KISIMs Symbolschrift hielt die App pauschal für ein Häkchen — in Wahrheit war es das Durchmesserzeichen im Gefässbefund."],
      ["22.9.2026", "Etappe 6: Standort-Fassungen und Ideen-Speicher",
       "Ein Baustein, je Arbeitsort der richtige Wortlaut: Bausteine können jetzt eigene Fassungen für das Spital Limmattal und die Praxis Neuromed tragen — angelegt im Bearbeiten-Fenster als Kopie der Standardfassung, erkennbar an der Marke „Standorte“. Die App kennt ihren Standort aus den Einstellungen (bewusst je Gerät, nie abgeglichen), das Windows-Skript aus seinem Menü, die Erweiterung aus dem Symbol-Fenster; ohne eigene Fassung gilt überall die Standardfassung, nichts scheitert still. Dazu der Ideen-Speicher: ein eigener Bereich für Wünsche an die App, mit Export als Dokument für den Bau-Chat. Und als Vorbereitung der Tabellen-Etappe sichert das Testwelt-Skript die Zwischenablage als RTF-Datei.",
       "Die ganze Etappe brauchte genau eine Nachbesserung: Das Bearbeiten-Fenster war mit zwei Standort-Fassungen höher als der Bildschirm, der Speichern-Knopf ausser Reichweite — seither scrollt der Inhalt und die Knopfzeile bleibt stehen. Und die ersten RTF-Proben aus KISIM kamen als leere Hüllen an, bis der Umweg über eine Mail sie heil vom Spital-Netzlaufwerk holte."],
      ["20.–21.9.2026", "Etappe 5: Arbeitsplatz gleichziehen",
       "Die Chrome-Erweiterung zieht mit dem Windows-Skript gleich: Auswahl-Fenster an der Schreibmarke (häufigste fünf zuoberst), Suche auch im Bausteintext, neun Zwischenspeicher-Fächer mit 12-Stunden-Frist, ;;neu mit Kontroll-Vorschau und Warnsatz als einziger Schreibweg — und Tab löst nichts mehr aus. Das Skript kennt neu seinen Standort (Spital Limmattal oder Praxis Neuromed), die Browser-Weiche als eigene Einstellung, das Diagnose-Kürzel ;;test mit kopierbarem Zustandsbericht und die gemerkte Anmeldung mit Windows-verschlüsseltem Passwort. Die Statistik zählt unter sprechenden Standortnamen. Alles trägt erstmals dieselbe Fassungsnummer.",
       "Zwei Wächter zeigten sich erst am echten Gerät: Smart App Control in der Praxis lässt AutoHotkey grundsätzlich nicht laufen — die Praxis arbeitet darum browserseitig mit der Erweiterung. Und ein Kürzel-Griff aus Etappe 4 (Strg+Alt fürs Fächer-Merken) entpuppte sich als AltGr-Falle: Er verschluckte am Spital das @-Zeichen, überall. Eine Einstellung, keine Zeile Code, gab es zurück."],
      ["18.–20.9.2026", "Etappe 4: Kürzel in allen Windows-Programmen",
       "Ein kleines Programm für Windows, das keine Installation braucht: Es holt die Bausteine aus derselben Ablage wie die App und macht ;;kürzel und Leertaste in JEDEM Programm zum fertigen Text — zuerst und vor allem in KISIM. Dazu ein Auswahl-Fenster, das beim Tippen die passenden Bausteine neben der Schreibmarke zeigt, eine Suche über Titel, Kürzel, Kategorie und Text, ein Ausfüll-Fenster für Lücken, neun Zwischenspeicher-Fächer mit ;;c und ;;v, und der Weg zurück: markierter Text aus KISIM wird mit ;;neu zum Entwurf in der App, samt Formatierung. Damit das Format überall stimmt, erzeugt die App beim Speichern das Druckformat gleich mit und legt es in einer neuen Spalte ab.",
       "Ein Test klärte eine alte Hoffnung: KISIM füllt seine eigenen Patienten-Makros nur aus, wenn der Text über KISIMs eigene Bausteine kommt. Eingefügter Text bleibt unangetastet — was zugleich die beruhigende Kehrseite hat, dass unser System die Patientendaten gar nie zu sehen bekommt."],
      ["17.–18.9.2026", "Etappe 3: Kürzel im Browser",
       "Eine Chrome-Erweiterung, die auf freigeschalteten Seiten ;;kürzel erkennt und den Baustein formatiert an der Schreibmarke einsetzt — Lücken-Fenster und Suche als Einblendung in der Seite, Übungsfeld zum gefahrlosen Ausprobieren, zwei Fassungen wie die App. Fünf App-Dateien reisen byteweise identisch mit, damit die Kürzel dieselbe Platzhalter-Sprache sprechen. In der Praxis in Axenita bewiesen, in einem Zug gebaut, ohne Nachbesserung an der Erweiterung.",
       "Der erste Praxis-Test scheiterte an nichts Technischem: Die Seite war nach dem Einschalten nicht neu geladen. Das Diagnose-Kürzel ;;qqq — bewusst unbekannt — zeigte in einer Sekunde, ob die Erweiterung mitliest. Und der Duplex-Befund aus KISIM bewies, dass Tabellen ihre eigene Etappe brauchen."],
      ["19.8.–13.9.2026", "Vorarbeit: die Machbarkeit",
       "Bevor eine Zeile der App entstand, wurde am Arbeitsrechner ohne Administratorrechte geprüft, was dort überhaupt möglich ist: Zwischenablage, Einfügen in KISIM, Dateizugriff, freies Internet — und mit einem eigenen Testpaket, ob systemweite Kürzel laufen.",
       "Alle Tests bestanden, auch der kritischste: AutoHotkey tippt aus einem einfachen Ordner heraus direkt in KISIM. Damit war klar, dass die App nichts einbüssen muss."],
      ["12.–13.9.2026", "Etappe 1: Das Bausteinfenster",
       "Bausteine anlegen, suchen, benutzen. Platzhalter für Datum, Zeit, Lücken, Auswahllisten, Konstanten und andere Bausteine. Papierkorb mit 30 Tagen, Export und Import mit Vorschau, Selbsttest, Statistik, ausführliche Anleitung, PDF-Berichte. Zwei getrennte Datenwelten (normal und Testdaten) von Anfang an.",
       "Der Formatierungs-Test am 13.9. schien ein klares Ergebnis zu bringen: KISIM nehme und gebe nur reinen Text. Das war falsch — und die Korrektur am 14.9. wurde zur wichtigsten Wendung des Projekts."],
      ["13.–17.9.2026", "Etappe 2: Abgleich, Formatierung, Veröffentlichung",
       "Anmeldung und Abgleich über eine gemeinsame Datenablage; zwei getrennte Projekte für Testdaten und Normalbetrieb. Formatierung im Baustein: fett, kursiv, unterstrichen, durchgestrichen, Schriftart, Grösse, Farbe, Markierung, Listen — mit Tastenkürzeln, die sich umbelegen lassen. Ein Leser für das Format, in dem KISIM kopiert. Entwürfe und Sammel-Erfassung für die Übernahme bestehender Bausteine. Und zum Schluss die Veröffentlichung im Netz: kein Ordner mehr, der herumgetragen werden muss.",
       "Näd widersprach dem Formatierungs-Ergebnis vom 13.9. — zu Recht. Drei Tests später war bewiesen: KISIM nimmt Formatierung sehr wohl an, es spricht nur eine andere Sprache als der Browser. Ohne diesen Widerspruch wäre die App dauerhaft auf reinen Text beschränkt geblieben."]
    ];
  }
  return { eintraege: eintraege };
})();
