// Datei: status-texte.js
// Projekt: Textbausteine — Teil: App (Browser) UND Chrome-Erweiterung
//          (byteweise Kopie — Prüfsuite: cmp)
// Zweck: Alle sichtbaren Texte des Status-Werks (TB.statusTexte) — in
//        Etappe 11 aus status.js ausgegliedert, weil die Datei über die
//        600-Zeilen-Grenze gewachsen war. Sie wird VOR status.js geladen.
//        texte.js bleibt davon unberührt (Erweiterungs-Kopie-Muster E8).

"use strict";
window.TB = window.TB || {};

TB.statusTexte = {
  bereichStatus: "Status",
  bereichUebersicht: "Übersicht",
  statusTitel: "Status-Werk",
  statusLeer: "Noch kein Gesamtstatus auf diesem Konto. Mit dem Knopf unten holst Du die mitgelieferte Grundausstattung — sie synct danach auf alle Geräte.",
  grundausstattungKnopf: "Grundausstattung übernehmen",
  grundausstattungNeuKnopf: "Grundausstattung neu laden",
  grundausstattungWarnung: "Das ersetzt Deinen bearbeiteten Gesamtstatus durch die Lieferfassung. Deine eigenen Status-Muster (Teilmengen) bleiben erhalten. Fortfahren?",
  grundausstattungFertig: "Grundausstattung übernommen.",
  teilmengenTitel: "Status wählen (mehrere möglich):",
  suchePlatzhalter: "Untersuchung suchen …",
  weitereZu: "Weitere Untersuchungen (%s) einblenden",
  weitereAuf: "Weitere Untersuchungen ausblenden",
  zaehlerZeile: "%s Untersuchungen gewählt · %s überschrieben",
  kopierenKnopf: "Kopieren",
  kopiertMeldung: "Status kopiert — am Zielort mit Strg+V (Mac: Cmd+V) einfügen.",
  kopiertNurText: "Status kopiert — nur als reiner Text (ohne Fett).",
  kopierenFehl: "Kopieren fehlgeschlagen.",
  nichtsGewaehlt: "Keine Untersuchung angekreuzt — es gibt nichts zu kopieren.",
  zuruecksetzenKnopf: "Alles zurücksetzen",
  zurueckgesetzt: "Maske geleert — nichts wurde gespeichert.",
  alsStatusKnopf: "Auswahl als eigenen Status speichern",
  alsStatusFrage: "Name des neuen Status:",
  alsStatusErsetzen: "„%s“ gibt es schon — Ankreuz-Muster ersetzen?",
  alsStatusFertig: "Status „%s“ gespeichert (nur das Ankreuz-Muster, keine Befunde).",
  pflegeKnopf: "Status-Pflege",
  zurueckZumAusfuellen: "Zurück zum Ausfüllen",
  vorschauTitel: "Vorschau",
  vorschauLeer: "(noch nichts angekreuzt)",
  abweichungZurueck: "Auf Normalbefund zurück",
  befundKlickHinweis: "Zum Überschreiben anklicken",
  nameKlickHinweis: "Klick kreuzt an oder ab",
  tardocFuerAFehlt: "Für %s A fehlen %s Gruppen — am nächsten: %s",
  tardocFuerAFehlt1: "Für %s A fehlt 1 Gruppe — am nächsten: %s",
  tardocErfuellt: "%s A erfüllt (%s Gruppen).",
  tardocKeine: "keine Gruppe begonnen",
  tardocHinweis: "Zählung nach %s: B = bis zu 3, A = ab 4 dokumentierte Gruppen. Die Ampel zählt nur Gruppen — ob die Exploration als eigenständige Leistung erbracht wurde (Neurostatus B 23 Min. / A 46 Min., Hirnnerven A 35 Min.), beurteilst Du; massgeblich bleibt der Tarif.",
  tardocPilleA: "%s: A (%s Gruppen)",
  tardocPilleB: "%s: B (%s von bis zu 3 Gruppen)",
  tardocPilleLeer: "%s: –",
  // Pflege
  pflegeTitel: "Status-Pflege",
  pflegeHinweis: "Änderungen wirken sofort und syncen auf alle Geräte. Häufige Untersuchungen stehen offen in der Maske, seltene hinter „Weitere“.",
  kategorieNeu: "Neue Kategorie",
  kategorieName: "Name der Kategorie:",
  kategorieLoeschenVoll: "Diese Kategorie enthält noch Untersuchungen — zuerst verschieben.",
  untersuchungNeu: "Neue Untersuchung",
  untersuchungLoeschenFrage: "„%s“ endgültig aus dem Gesamtstatus entfernen?",
  haeufigMarke: "häufig",
  seltenMarke: "selten",
  feldName: "Untersuchung",
  feldNormal: "Normalbefund",
  feldKategorie: "Kategorie",
  feldHaeufig: "Häufig untersucht (steht offen in der Maske)",
  feldTardoc: "Tardoc-Etiketten",
  tardocKeineEtiketten: "keine",
  tardocNeu: "Etikett dazu",
  tardocArt: "Statusart",
  tardocGruppe: "Gruppe",
  tardocMerkmale: "Merkmale (mit Komma getrennt)",
  tardocMuskeln: "Anzahl Muskeln",
  teilmengePflegeTitel: "Eigene Status (Ankreuz-Muster)",
  teilmengeUmbenennen: "Umbenennen",
  teilmengeLoeschen: "Löschen",
  teilmengeLoeschenFrage: "Status „%s“ löschen? (Der Gesamtstatus bleibt unberührt.)",
  speichern: "Speichern",
  abbrechen: "Abbrechen",
  loeschenKnopf: "Löschen",
  gespeichert: "Gespeichert.",
  hoch: "▲", runter: "▼",
  nurGewaehlteKnopf: "Nur Gewählte und Zusätze",
  ziehenHinweis: "Zum Verschieben an diesem Griff (oder der ganzen Zeile) ziehen und an der gewünschten Stelle loslassen — auch in eine andere Kategorie",
  zusatzAn: "Zusatz dieses Status: erscheint beim Laden sichtbar, aber nicht angewählt — Klick nimmt ihn wieder raus",
  zusatzAus: "Als Zusatz vormerken: wird mit „Als eigenen Status speichern“ dem Status mitgegeben und erscheint dann beim Laden sichtbar, aber nicht angewählt",
  muskelnKnopf: "Muskeln (%s/%s)",
  muskelnHinweis: "Einzelne Muskeln an- und abwählen — der Text nennt nur die gewählten",
  muskelnKeine: "keine Defizite.",
  merkmaleAlleAn: "alle wählen",
  merkmaleAlleAb: "alle abwählen",
  zusatzMuskelAn: "Zusatz-Muskel dieses Status: erscheint gelb markiert, aber nicht angewählt — Klick nimmt ihn wieder raus",
  zusatzMuskelAus: "Als Zusatz-Muskel vormerken: wird mit „Als eigenen Status speichern“ dem Status mitgegeben",
  tardocLesenKnopf: "Tardoc-Kriterien nachlesen",
  tardocLesenTitel: "Tardoc-Kriterien (TARDOC 1.4c)",
  tardocLesenEinleitung: "Von Claude zusammengefasst, eng am Original — zum Prüfen führt jeder Positions-Titel direkt auf die Position im LKAAT-Browser (öffnet in neuem Tab).",
  tardocLesenB: "%s (%s): dokumentierte Untersuchung und Beurteilung von bis zu 3 der untenstehenden Gruppen%s.",
  tardocLesenA: "%s (%s): dokumentierte Untersuchung und Beurteilung von 4 oder mehr Gruppen%s.",
  tardocLesenMin: " — hinterlegt mit %s Minuten",
  tardocLesenGruppe: "Gruppe %s · %s — mind. %s: ",
  tardocLesenGruppeMuskeln: "Gruppe %s · %s — mind. %s Muskeln: ",
  tardocLesenZu: "Schliessen",
  tardocLesenGruppeKopf: "Gruppe — Mindestzahl",
  tardocLesenGleich: "Was in einer Gruppe dokumentiert sein muss, ist bei B und A laut Tarif identisch (die Zellen sind darum in beiden Spalten gleich). Der Unterschied steht in der Kopfzeile: B verlangt bis zu 3 dieser Gruppen, A verlangt 4 oder mehr — bei entsprechend längerer hinterlegter Dauer.",
  tardocLesenStand: "Stand der Zusammenfassung: 27.09.2026, Links 30.09.2026. Massgeblich ist immer der Originaltext des Tarifs.",
  exportKnopf: "Status als Datei sichern",
  exportHinweis: "Sichert Gesamtstatus und eigene Status als Datei — zum Aufheben oder zum Schicken an Claude, damit Deine Änderungen in die Grundausstattung einfliessen können.",
  exportFertig: "Status-Datei erstellt: %s",
  seltenZeigen: "Seltene anzeigen (%s)",
  seltenVerbergen: "Seltene ausblenden",
  seltenHaekchen: "selten",
  kuerzelKnopf: "Kürzel",
  kuerzelFrage: "Kürzel dieses Status (ohne ;;) — damit öffnet ;;kürzel das Status-Fenster am Arbeitsplatz. Leer = automatisch aus dem Namen:",
  kuerzelDoppelt: "Das Kürzel „%s“ trägt schon der Status „%s“.",
  kuerzelBelegt: "Achtung: Ein Baustein trägt schon das Kürzel „%s“ — der Baustein hat am Arbeitsplatz Vorrang.",
  fensterHinweis: "Ausfüllen wie gewohnt — der Knopf übergibt alles ans Skript, das Fenster schliesst sich.",
  fensterKnopf: "An KISIM übergeben",
  tardocPfeil: "Einzelheiten ein-/ausblenden",
  tardocPfeilWort: "Einzelheiten",
  fensterUebergeben: "Übergeben ✓ — Fenster schliesst sich …",
  fensterLeer: "Noch nichts zum Übergeben — bitte zuerst ausfüllen.",
  fensterFehler: "Die Zwischenablage liess sich nicht beschreiben — bitte noch einmal auf den Knopf drücken.",
  fensterKeinStatus: "Kein Status mit dem Kürzel „%s“ gefunden — das Status-Werk öffnet leer."
};
