// Datei: texte.js
// Projekt: Textbausteine — Teil: App (Browser)
// Zweck: ALLE sichtbaren Texte der Oberfläche an einem Ort. Wer eine
//        Beschriftung ändern will, ändert sie hier — nirgends sonst.
//        Keine englischen Begriffe in der Oberfläche.

"use strict";
window.TB = window.TB || {};

TB.T = {
  // Kopf und Bereiche
  bereichBausteine: "Bausteine",
  bereichEntwuerfe: "Entwürfe",
  bereichPapierkorb: "Papierkorb",
  bereichEinstellungen: "Einstellungen",
  bereichSelbsttest: "Selbsttest",
  bereichHilfe: "Anleitung",
  bereichStatistik: "Statistik",
  bereichChronik: "Chronik",
  chronikBesonders: "Besonderer Moment: ",

  // Liste
  suchfeld: "Suchen … (Titel, Kürzel, Kategorie, Text)",
  alleKategorien: "Alle Kategorien",
  zuletztBenutzt: "Zuletzt benutzt",
  ohneKategorie: "Ohne Kategorie",
  leererBestand: "Noch keine Bausteine. Mit „+ Neu“ legst Du den ersten an — zwei Beispiele findest Du über Einstellungen → Beispiele einfügen.",
  keineTreffer: "Kein Baustein passt zur Suche.",
  wirdGeladen: "Daten werden geladen …",
  neuKnopf: "+ Neu",
  bearbeitenKnopf: "Bearbeiten",
  loeschenKnopf: "In den Papierkorb",

  // Bearbeiten
  neuTitel: "Neuer Baustein",
  bearbeitenTitel: "Baustein bearbeiten",
  feldTitel: "Titel",
  feldKuerzel: "Kürzel (ohne Strichpunkt — er wird automatisch vorangestellt)",
  feldKategorie: "Kategorie",
  feldText: "Text (mit Platzhaltern wie {{Datum}})",
  feldNotiz: "Notiz (nur für Dich, wird nie eingefügt)",
  speichern: "Speichern",
  abbrechen: "Abbrechen",
  vorschau: "Vorschau",
  gespeichert: "Gespeichert.",
  huckepackGewandelt: "Die mitgebrachte KISIM-Formatierung wurde übernommen — mit dem Speichern gehört sie fest zum Baustein.",
  nichtGespeichert: "NICHT gespeichert: ",
  fehlerTitelFehlt: "Der Titel fehlt.",
  fehlerKuerzelDoppelt: "Dieses Kürzel hat schon der Baustein „%s“.",
  fehlerKuerzelZeichen: "Das Kürzel darf keine Leerzeichen und keinen Strichpunkt enthalten.",
  makroWarnung: "Platzhalter-Prüfung — bitte anschauen:",
  makroOk: "Platzhalter-Prüfung: in Ordnung.",
  einfuegenTitel: "Platzhalter einfügen (setzt das Gerüst an die Cursor-Stelle):",
  knopfDatum: "Datum",
  knopfZeit: "Zeit",
  knopfFeld: "Lücke zum Ausfüllen",
  knopfAuswahl: "Auswahl",
  knopfKonstante: "Konstante",
  knopfBaustein: "Anderer Baustein",
  knopfTrenner: "Trennzeichen |",

  // Benutzen / Makro-Dialog
  ausfuellenTitel: "Lücken ausfüllen",
  kopieren: "Kopieren",
  kopiert: "Kopiert — mit Strg+V (Mac: ⌘V) einfügen.",
  kopiertMarken: "Kopiert — einfügen, dann die Marken der Reihe nach andiktieren.",
  kopierenFehlgeschlagen: "Kopieren fehlgeschlagen — Text markieren und von Hand kopieren.",
  vorschauTitel: "So sieht der Text aus:",

  // Papierkorb
  papierkorbLeer: "Der Papierkorb ist leer. Gelöschte Bausteine bleiben hier 30 Tage.",
  zurueckholen: "Zurückholen",
  endgueltigLoeschen: "Endgültig löschen",
  zurueckgeholt: "Zurückgeholt.",
  inPapierkorb: "In den Papierkorb gelegt (30 Tage aufbewahrt).",
  endgueltigFrage: "%s Baustein(e) endgültig löschen? Das kann nicht rückgängig gemacht werden.",
  endgueltigGeloescht: "Endgültig gelöscht.",
  geloeschtAmText: "gelöscht am ",

  // Einstellungen
  einstAnzeigename: "Name der App (erscheint oben und im Fenstertitel)",
  einstDatumsformat: "Datumsformat für {{Datum}} (TT = Tag, MM = Monat, JJJJ = Jahr)",
  einstKonstanten: "Eigene Konstanten — im Baustein als {{Name}} verwendbar",
  einstKonstanteName: "Name",
  einstKonstanteWert: "Wert",
  einstKonstanteNeu: "+ Konstante",
  einstKonstanteLoeschen: "Entfernen",
  einstFaecherTitel: "Zwischenspeicher-Kürzel (Windows-Skript)",
  einstFaecherText: "Neun Fächer, wie Strg+C und Strg+V: Mit ;;c1 legst Du die Zwischenablage in Fach 1, mit ;;v1 setzt Du sie von dort ein. Den Buchstaben bestimmst Du hier selbst, die Ziffer 1 bis 9 bleibt. Gilt auf allen Geräten.",
  fachMerken: "Buchstabe zum Merken (wie Strg+C)",
  fachEinsetzen: "Buchstabe zum Einsetzen (wie Strg+V)",
  fachGleich: "Beide Buchstaben sind gleich — bitte unterschiedlich wählen.",
  fachVerdeckt: "Achtung, diese Bausteine werden dadurch verdeckt: ",
  fachTastenTitel: "Tastenkombination zum Merken",
  fachTastenStrgAlt: "Strg + Alt + Ziffer",
  fachTastenStrgUmschalt: "Strg + Umschalt + Ziffer",
  fachTastenAus: "keine (nur ;;-Kürzel)",
  einstGeraetTitel: "Name dieses Geräts",
  einstGeraetText: "Er erscheint in der Statistik und bei einer doppelten Änderung, damit Du die Geräte auseinanderhältst. Er bleibt IMMER auf diesem Gerät und wird nie abgeglichen.",
  einstExportTitel: "Sicherung",
  einstExportText: "Der Abgleich ersetzt die Sicherung nicht: Er verteilt Deine Bausteine, er bewahrt sie nicht auf. Zieh darum ab und zu eine Export-Datei — besonders vor grösseren Änderungen.",
  exportKnopf: "Alle Bausteine exportieren (Datei)",
  importKnopf: "Aus Datei importieren …",
  exportFertig: "Export-Datei erstellt: ",
  importTitel: "Import — das würde passieren:",
  importNeu: "neu hinzukommen",
  importVorhanden: "schon vorhanden (bleiben unverändert)",
  importZurueck: "aus dem Papierkorb zurückholen",
  importAnwenden: "Import ausführen",
  importFertig: "Import fertig: %s neu, %s unverändert, %s zurückgeholt.",
  importFehler: "Diese Datei kann nicht gelesen werden: ",
  beispieleKnopf: "Beispiele einfügen (2 Bausteine)",
  beispieleFertig: "Beispiele eingefügt.",
  ueberTitel: "Über die App",
  fassung: "Fassung",
  welt: "Datenwelt",
  weltDev: "DEV (Testdaten, roter Rahmen)",
  weltProd: "Normal",
  geraetName: "Gerät",

  // Selbsttest und Berichte
  selbsttestKnopf: "Selbsttest starten",
  selbsttestLaeuft: "Selbsttest läuft …",
  kategorieSelbsttest: "Selbsttest",
  kategorieStatistik: "Statistik",
  kategorieVerbindung: "Verbindung",
  berichtKopieren: "Bericht kopieren",
  berichtKopiert: "Bericht kopiert — als Nachricht an Claude einfügbar.",
  berichtPdf: "Als PDF sichern (+ Text kopieren)",
  berichtPdfFertig: "Druckfenster offen — dort „Als PDF sichern“ wählen. Der Text liegt bereits in der Zwischenablage.",
  berichtPdfBlockiert: "Der Browser hat das Druckfenster blockiert — bitte Pop-up-Fenster für diese Seite erlauben.",

  // Statistik
  statistikTitel: "Statistik",
  statistikErklaerung: "Gezählt wird, WIE OFT etwas benutzt wird — nie, was darin steht. Es werden keine Texte und keine Patientendaten gespeichert.",
  statistikSeit: "Gezählt seit ",
  statistikGesamt: "Bausteine insgesamt eingefügt: ",
  statistikBausteine: "Meistbenutzte Bausteine",
  statistikFunktionen: "Benutzte Funktionen",
  statistikGeraete: "Verteilung auf die Geräte",
  statistikLeer: "Noch nichts gezählt.",
  statistikMal: "×",
  statistikZuletzt: "zuletzt ",
  statistikZuruecksetzen: "Zählung zurücksetzen",
  statistikZurueckgesetzt: "Zählung zurückgesetzt.",
  statistikFrage: "Die ganze Zählung auf null setzen? Die Bausteine bleiben unverändert. Das gilt nur für dieses Gerät; die Zahlen der anderen Geräte bleiben stehen.",
  statistikEntfernt: "(gelöschter Baustein)",
  statistikDiesesGeraet: "dieses Gerät",

  // Anmeldung
  anmeldenTitel: "Anmelden",
  anmeldenText: "Melde Dich einmal je Gerät an. Danach bleibt das Gerät angemeldet, bis Du hier abmeldest.",
  anmeldenMail: "E-Mail-Adresse",
  anmeldenPasswort: "Passwort",
  anmeldenKnopf: "Anmelden",
  anmeldenLaeuft: "Anmeldung läuft …",
  anmeldenFertig: "Angemeldet.",
  abmeldenKnopf: "Abmelden",
  abmeldenFrage: "Wirklich abmelden? Deine Bausteine bleiben auf diesem Gerät, werden aber nicht mehr abgeglichen.",
  abmeldenOffenFrage: "%s Änderung(en) sind noch nicht hochgeladen. Beim Abmelden bleiben sie auf diesem Gerät liegen. Trotzdem abmelden?",
  abmeldenFertig: "Abgemeldet.",
  nichtAngemeldet: "Nicht angemeldet — es wird nichts abgeglichen.",
  nichtEingerichtet: "Die Zugangsdaten fehlen noch. Trag sie in der Datei konfiguration.js ein (Adresse und öffentlicher Schlüssel aus dem Supabase-Fenster).",

  // Abgleich
  abgleichTitel: "Abgleich",
  abgleichJetzt: "Jetzt abgleichen",
  abgleichLaeuft: "gleicht ab …",
  abgleichNie: "noch nie abgeglichen",
  abgleichVor: "abgeglichen vor ",
  abgleichGeradeEben: "gerade eben abgeglichen",
  abgleichAutomatisch: " · gleicht jede Minute von selbst ab",
  abgleichMinuten: " Minuten",
  abgleichStunden: " Stunden",
  abgleichTagen: " Tagen",
  abgleichOffen: "%s wartet auf den Abgleich",
  abgleichFertig: "Abgeglichen.",
  abgleichNeues: "%s Änderung(en) von einem anderen Gerät übernommen.",
  abgleichNichtEingerichtet: "Zugangsdaten fehlen (konfiguration.js).",
  abgleichNichtAngemeldet: "Nicht angemeldet.",
  abgleichErstmalsTitel: "Zum ersten Mal abgleichen",
  abgleichErstmalsText: "Auf diesem Gerät liegen %s Baustein(e), die noch nie abgeglichen wurden. Sie werden jetzt hochgeladen und stehen danach auf allen Deinen Geräten. Nichts wird gelöscht.",
  abgleichErstmalsKnopf: "Hochladen und abgleichen",
  abgleichRatschlagExport: "Tipp: Zieh vorher in den Einstellungen eine Export-Datei.",

  // Fehlermeldungen aus dem Netz — verständlich, nicht als Nummer
  wolkeFehlerNetz: "Keine Verbindung zur Datenablage. Die App arbeitet weiter; es wird nur nicht abgeglichen.",
  wolkeFehlerAnmeldung: "E-Mail oder Passwort stimmt nicht.",
  wolkeFehlerGesperrt: "Die Datenablage nimmt keine neuen Konten an (das ist so gewollt).",
  wolkeFehlerAbgemeldet: "Die Anmeldung ist abgelaufen — bitte neu anmelden.",
  wolkeFehlerTabelle: "Die Tabellen fehlen in diesem Projekt. Das Einrichtungs-Drehbuch, Schritt 2, wurde noch nicht ausgeführt.",
  wolkeFehlerZuVielt: "Zu viele Versuche kurz nacheinander — in ein paar Minuten nochmals.",
  wolkeFehlerPause: "Die Datenablage antwortet nicht. Möglicherweise ist das Projekt nach einer Woche ohne Zugriff pausiert — im Supabase-Fenster auf „Restore“ klicken.",
  wolkeFehlerAllgemein: "Die Datenablage meldet einen Fehler.",

  // Verbindung prüfen
  verbindungTitel: "Verbindung prüfen",
  verbindungText: "Beantwortet vier Fragen getrennt: Sind die Zugangsdaten da? Kommt die Adresse von hier aus durch? Ist die Zeilen-Sicherheit scharf? Sind die Tabellen erreichbar? Diese Prüfung gehört an jedem Ort einmal gemacht — besonders am Arbeitsrechner.",
  verbindungKnopf: "Verbindung prüfen",
  verbindungLaeuft: "Prüfung läuft …",
  pruefEingerichtet: "Zugangsdaten eingetragen",
  pruefEingerichtetNein: "konfiguration.js ist noch nicht ausgefüllt",
  pruefErreichbar: "Adresse von hier aus erreichbar",
  pruefAntwort: "Antwort ",
  pruefRegistrierung: "Selbstregistrierung abgeschaltet",
  pruefRegistrierungOffen: "OFFEN — Fremde könnten ein Konto anlegen. Drehbuch Schritt 5 nachholen.",
  pruefRegistrierungZu: "abgeschaltet",
  pruefSicherheit: "Zeilen-Sicherheit scharf",
  pruefSicherheitGut: "abgemeldet wird nichts ausgeliefert",
  pruefSicherheitSchlecht: "ACHTUNG: ohne Anmeldung sind Zeilen lesbar. Drehbuch Schritt 2 und 3 prüfen.",
  pruefAngemeldet: "Auf diesem Gerät angemeldet",
  pruefAngemeldetNein: "nicht angemeldet — die Tabellen wurden darum nicht geprüft",
  pruefTabelle: "Tabelle erreichbar: ",
  pruefTabelleGut: "antwortet",
  pruefSpalten: "Tabelle kennt alle Felder der App",
  pruefSpaltenGut: "alle Spalten vorhanden",
  pruefSpaltenSchlecht: "Eine Spalte fehlt — das Drehbuch ist älter als die App. Meldung:",

  // Konflikte
  konfliktTitel: "Derselbe Baustein wurde an zwei Orten geändert",
  konfliktText: "Es wird nichts überschrieben, bevor Du gewählt hast.",
  konfliktEigen: "Fassung von diesem Gerät (%s)",
  konfliktFremd: "Fassung vom anderen Gerät",
  konfliktGeaendert: "geändert am ",
  konfliktNimmEigen: "Diese behalten",
  konfliktNimmFremd: "Andere behalten",
  konfliktNimmBeide: "Beide behalten",
  konfliktZusatz: " (zweite Fassung)",
  konfliktGeloest: "Entschieden.",
  konfliktAnzahl: "%s Baustein(e) brauchen Deine Entscheidung",
  konfliktAnsehen: "Ansehen",

  // Formatierter Text und Platzhalter
  reichtextZerrissen: "%s Platzhalter ist mitten drin formatiert — er wirkt so nicht. Bitte die Auszeichnung über den GANZEN Platzhalter legen oder ganz entfernen.",
  reichtextTiefe: "Zu viele ineinander verschachtelte Bausteine (höchstens drei Ebenen).",
  reichtextKreis: "Der Baustein „%s“ ruft sich selbst auf — das würde nie enden.",
  reichtextUnbekannt: "Es gibt keinen Baustein mit dem Kürzel „%s“.",
  reichtextMarkeDoppelt: "Im Text stehen schon eckige Klammern. Beim Diktieren wären das zusätzliche Marken — bitte andere Zeichen wählen oder die Ausgabeart „Fenster“ benutzen.",

  // Ausgabeart je Baustein
  artTitel: "Wie sollen die Lücken ausgefüllt werden?",
  artFenster: "Vorher fragen (Fenster)",
  artFensterText: "Die Lücken werden abgefragt, der Text kommt fertig ins Zielprogramm. Sicher — es bleibt nie etwas Unausgefülltes stehen.",
  artMarken: "Als Marken mitliefern (Diktat)",
  artMarkenText: "Der Text wird sofort eingefügt, die Lücken bleiben als [Beschriftung] stehen. Zum Andiktieren mit Dragon oder dem Speech Mike. VORSICHT: Eine übersprungene Marke bleibt im Befund stehen.",
  artMarkeZeichen: "Zeichen um die Marken (muss zu Dragon passen)",
  markeKennzeichen: "Marken",

  // Entwürfe und Sammel-Erfassung
  entwurfListe: "Entwürfe (%s)",
  entwurfLeer: "Noch keine Entwürfe. Oben einfügen oder in der Bausteinliste auf „+ Idee“.",
  entwurfOhneTitel: "(ohne Titel)",
  entwurfFertig: "Als fertig markieren",
  entwurfFertigTitel: "Entwurf fertigstellen",
  entwurfFertigText: "Der Entwurf behält seine Kennung — er wird nicht kopiert, sondern wächst auf. Verweise aus anderen Bausteinen zeigen weiterhin darauf.",
  entwurfFertigKnopf: "Fertigstellen",
  entwurfIstFertig: "Der Entwurf ist jetzt ein fertiger Baustein.",
  ideeKnopf: "+ Idee",
  ideeTitel: "Schnelle Idee",
  ideeText: "Ein Feld, sonst nichts. Titel und Kürzel kommen später. Mit Strg+Enter (Mac: ⌘+Enter) direkt sichern.",
  ideeSichern: "Als Entwurf sichern",
  ideeGesichert: "Als Entwurf gesichert.",
  sammelTitel: "Sammel-Erfassung",
  sammelText: "Für die Übernahme Deiner bestehenden Bausteine: im Quellprogramm kopieren, hier einfügen, Eingabetaste — und der nächste. Jeder Eintrag wird ein Entwurf. Die Formatierung kommt mit. Umschalt+Eingabetaste macht einen Absatz INNERHALB des Entwurfs.",
  sammelPlatzhalter: "Hier einfügen, dann Eingabetaste …",
  sammelUebernehmen: "Übernehmen (Eingabetaste)",
  sammelRueckgaengig: "Letzten rückgängig",
  sammelStand: "In dieser Sitzung erfasst: %s · Entwürfe insgesamt: %e",
  sammelLeer: "Das Feld ist leer.",
  sammelNichtsRueckgaengig: "In dieser Sitzung wurde noch nichts erfasst.",
  sammelZurueckgenommen: "Zurückgenommen.",

  // Zwischenablage untersuchen
  untersuchTitel: "Zwischenablage untersuchen",
  untersuchText: "Für die Abklärung, wenn aus einem Programm etwas anders ankommt als erwartet. Im Programm kopieren, dann unten ins Feld klicken und Strg+V drücken. Darunter erscheint, was die Zwischenablage wirklich enthält — reiner Text, HTML und RTF — und was die App daraus macht.",
  untersuchHier: "Hier hineinklicken und mit Strg+V einfügen …",
  untersuchKopieren: "Untersuchung kopieren",

  // Tastenkürzel
  kuerzelTitel: "Tastenkürzel fürs Formatieren",
  kuerzelText: "Gilt im Schreibfeld beim Bearbeiten eines Bausteins. Die Vorgabe entspricht Word. Zum Ändern auf das Feld klicken und die gewünschte Tastenkombination drücken. Die Belegung wird abgeglichen und gilt auf allen Deinen Geräten.",
  kuerzelDruecke: "Jetzt Tasten drücken …",
  kuerzelZuruecksetzen: "Auf die Vorgaben zurücksetzen",
  kuerzelGeaendert: "Tastenkürzel geändert.",
  kuerzelLeer: "Kein Tastendruck erkannt.",
  kuerzelGesperrt: "%s behält der Browser für sich — diese Kombination erreicht die App nie.",
  kuerzelBelegtApp: "Diese Kombination ist in der App schon für „%s“ belegt.",
  kuerzelDoppelt: "Diese Kombination ist schon für „%s“ belegt.",
  kuerzelOhneZusatz: "Bitte mit Strg (Mac: ⌘) oder Alt kombinieren, sonst stört es beim Schreiben.",
  kuerzel_fett: "Fett",
  kuerzel_kursiv: "Kursiv",
  kuerzel_unterstrichen: "Unterstrichen",
  kuerzel_durchgestrichen: "Durchgestrichen",
  kuerzel_liste: "Aufzählung",
  kuerzel_nummern: "Nummerierte Liste",
  kuerzel_sauber: "Auszeichnungen entfernen",

  // Formatierungsleiste
  formFett: "Fett",
  formKursiv: "Kursiv",
  formUnterstrichen: "Unterstrichen",
  formDurchgestrichen: "Durchgestrichen",
  formListe: "Aufzählung",
  formNummern: "Nummerierte Liste",
  formFarbe: "Schriftfarbe",
  formMarkierung: "Markierung",
  formSchriftart: "Schriftart",
  formGroesse: "Schriftgrösse",
  formSauber: "Auszeichnungen entfernen",
  formVorgabe: "(Vorgabe)",
  formHinweisZiele: "Nicht jedes Ziel kann alles: Axenita kennt fett, kursiv, unterstrichen, Schriftfarbe und Listen — Schriftgrösse und Markierung verwirft es. KISIM und Word können alles.",

  // Standort-Varianten (Etappe 6)
  standortTitel: "Standort dieses Geräts",
  standortText: "Diese Einstellung bleibt auf DIESEM Gerät — sie wird bewusst nicht abgeglichen, denn der Spitalrechner und der Praxisrechner sollen verschieden bleiben. Ein Baustein mit Standort-Fassungen liefert dann automatisch die passende Fassung; alle anderen Bausteine bleiben, wie sie sind.",
  standortKeiner: "(kein Standort — immer die Standardfassung)",
  standortGespeichert: "Standort gemerkt — gilt nur auf diesem Gerät.",
  variantenTitel: "Standort-Fassungen",
  variantenText: "Braucht dieser Baustein an einem Arbeitsort einen anderen Wortlaut (Briefkopf, Medikamentenliste), bekommt er hier eine eigene Fassung je Standort. Ohne eigene Fassung gilt überall die Standardfassung oben.",
  varianteAnlegen: "Fassung für %s anlegen",
  varianteLoeschen: "Fassung löschen",
  varianteFeld: "Fassung: %s",
  varianteGeloescht: "Standort-Fassung entfernt — es gilt wieder die Standardfassung.",
  markeVarianten: "Standorte",
  benutztVariante: " — Fassung %s",
  fehlerVariante: "Fassung %s: %f",

  // Ideen-Speicher (Etappe 6)
  bereichIdeen: "Ideen",
  ideenTitel: "Ideen-Speicher",
  ideenText: "Wünsche und Ideen für die Weiterentwicklung dieser App — damit nichts verloren geht. Von hier wandern sie als Dokument in den Bau-Chat. (Für halbfertige BAUSTEINE gibt es weiterhin die Entwürfe.)",
  ideenNeuTitel: "Kurzer Titel der Idee",
  ideenNeuText: "Worum geht es? (so viel oder wenig Du willst)",
  ideenFesthalten: "Idee festhalten",
  ideenLeer: "Noch keine Ideen. Oben die erste festhalten.",
  ideenGesichert: "Idee festgehalten — auf allen Geräten.",
  ideenEinplanen: "eingeplant",
  ideenWiederOffen: "wieder offen",
  ideenVerwerfen: "Verwerfen",
  ideenVerworfen: "Idee in den Papierkorb gelegt.",
  ideenOffen: "Offene Ideen",
  ideenEingeplant: "Eingeplant",
  ideenExport: "Als Dokument für den Bau-Chat sichern (.md)",
  ideenExportiert: "Dokument erzeugt — im Downloads-Ordner.",
  ideenStandTitel: "Ideen-Bericht",

  // Allgemein
  schliessen: "Schliessen",
  ok: "OK"
};
